package operators;

import static net.mindview.util.Print.print;

public class E12_UnsignedRightShift {
    public static void main(String[] args) {
        int i = -1 << 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i)+"-->"+i);
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
    }
}